### ISSUE TITLE
Omit using whole framework

### ISSUE THREAD

**Issue by igormukhingmailcom** [forikal-uk/capture-lookups#5]
This is my suggestions:
- Remove symfony/symfony from dependencies and use only symfony/console and other separate components
- Use Symfony\Component\Console\Application rather than Symfony\Bundle\FrameworkBundle\Console\Application which require AppKernel (and so whole Symfony Framework)
- Look how https://github.com/forikal-uk/xmlauthor-example-command organized as an example what I suggest

**Comment by forikal-uk** [comment]
Sounds like a good idea.

Thanks @igormukhingmailcom 

Because I have tested the current state quite thoroughly I have tagged it as [the first release](https://github.com/forikal-uk/capture-lookups/releases/tag/v1.0.0).

So, I will add you to the repo and you can make improvements.

**Comment by igormukhingmailcom** [comment]
I've removed tag `v1.0.0` and marked current state as `v0.1.0`. 
Just to follow current style. Once code will be refactored - it will be marked as `v0.2.0`. 
That way all tools/project/libraries having tags `v0.2.*` will be compatible each with other.

**Comment by igormukhingmailcom** [comment]
It was done and marked as `v0.2.0`

**Comment by forikal-uk** [comment]
Thanks @igormukhingmailcom
